pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        
        stage('Build') {
            steps {
                dir('eazyera') { // Change to the Angular project directory
                    script {
                        sh 'ng build'
                    }
                }
            }
        }
        
        stage('Unit Tests') {
            steps {
                dir('eazyera') { // Change to the Angular project directory
                    script {
                        sh 'ng test --watch=false --code-coverage'
                    }
                }
            }
        }
        
        stage('E2E Tests') {
            steps {
                dir('eazyera') { // Change to the Angular project directory
                    script {
                        sh 'ng e2e'
                    }
                }
            }
        }
        
        // Add more stages if needed, e.g., for deployment
    }
    
    post {
        always {
            // Cleanup, archiving artifacts, or publishing results can be done here
        }
    }
}
