pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        
        stage('Install Dependencies') {
            steps {
                sh 'npm install'
            }
        }
        
        stage('Build') {
            steps {
                sh 'ng build'
            }
        }
        
        stage('Unit Tests') {
            steps {
                sh 'ng test --watch=false --code-coverage'
            }
        }
        
        stage('E2E Tests') {
            steps {
                sh 'ng e2e'
            }
        }
    }
    
    post {
        always {
            echo 'Pipeline execution is complete.'
        }
    }
}
